# ASCII-only helper: writes new_project.ps1 with UTF-8 BOM
$targetPath = "e:\my_project\知识研究\.agents\skills\子项目管理\scripts\new_project.ps1"
$enc = [System.Text.UTF8Encoding]::new($true)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('<#')
$lines.Add('.SYNOPSIS')
$lines.Add('    Create a new sub-project folder under output/')
$lines.Add('.DESCRIPTION')
$lines.Add('    Creates a versioned sub-project directory following naming convention:')
$lines.Add('    output\{Number}_{Topic}_v1.0.0')
$lines.Add('    Inside the project, creates three sub-folders:')
$lines.Add('      01_问题答疑_v0.0.0\   (empty placeholder)')
$lines.Add('      02_课题研究_v0.0.0\   (empty placeholder)')
$lines.Add('      03_代码程序_v0.0.0\   (empty placeholder)')
$lines.Add('    Also initializes 版本记录.md and 目录.md (三节格式) inside.')
$lines.Add('.PARAMETER Topic')
$lines.Add('    The topic/domain name in Chinese (required)')
$lines.Add('.PARAMETER OutputRoot')
$lines.Add('    The root output directory. Defaults to the workspace output folder.')
$lines.Add('.EXAMPLE')
$lines.Add('    .\new_project.ps1 -Topic "减肥第一性原理"')
$lines.Add('    # Creates: output\01_减肥第一性原理_v1.0.0\')
$lines.Add('#>')
$lines.Add('')
$lines.Add('param(')
$lines.Add('    [Parameter(Mandatory=$true)]')
$lines.Add('    [string]$Topic,')
$lines.Add('')
$lines.Add('    [Parameter(Mandatory=$false)]')
$lines.Add('    [string]$OutputRoot = ""')
$lines.Add(')')
$lines.Add('')
$lines.Add('$utf8WithBom = New-Object System.Text.UTF8Encoding $true')
$lines.Add('$utf8NoBom = New-Object System.Text.UTF8Encoding $false')
$lines.Add('')
$lines.Add('function Ensure-Directory {')
$lines.Add('    param([string]$Path)')
$lines.Add('    if (-not (Test-Path -LiteralPath $Path)) {')
$lines.Add('        New-Item -ItemType Directory -Path $Path -Force | Out-Null')
$lines.Add('    }')
$lines.Add('}')
$lines.Add('')
$lines.Add('function Get-MemoryVersionFromText {')
$lines.Add('    param([string]$Text)')
$lines.Add('    if ($Text -match ''<!--\s*memory-version:\s*(\d+)\.(\d+)\.(\d+)\s*-->'') {')
$lines.Add('        return @{')
$lines.Add('            Text = "$($Matches[1]).$($Matches[2]).$($Matches[3])"')
$lines.Add('            Major = [int]$Matches[1]')
$lines.Add('            Minor = [int]$Matches[2]')
$lines.Add('            Patch = [int]$Matches[3]')
$lines.Add('        }')
$lines.Add('    }')
$lines.Add('    return @{')
$lines.Add('        Text = "1.0.0"')
$lines.Add('        Major = 1')
$lines.Add('        Minor = 0')
$lines.Add('        Patch = 0')
$lines.Add('    }')
$lines.Add('}')
$lines.Add('')
$lines.Add('function Update-GlobalKnowledgeMap {')
$lines.Add('    param(')
$lines.Add('        [string]$WorkspaceRoot,')
$lines.Add('        [string]$Topic,')
$lines.Add('        [string]$FolderName')
$lines.Add('    )')
$lines.Add('')
$lines.Add('    $memoryDir = Join-Path $WorkspaceRoot ".memory"')
$lines.Add('    $historyDir = Join-Path $WorkspaceRoot ".history\.memory\全局知识地图"')
$lines.Add('    $mapPath = Join-Path $memoryDir "全局知识地图.md"')
$lines.Add('    Ensure-Directory $memoryDir')
$lines.Add('    Ensure-Directory $historyDir')
$lines.Add('')
$lines.Add('    $todayDate = Get-Date -Format "yyyy-MM-dd"')
$lines.Add('    $row = "| $Topic | $FolderName | $todayDate | 进行中 | - |"')
$lines.Add('')
$lines.Add('    if (Test-Path -LiteralPath $mapPath) {')
$lines.Add('        $mapText = [System.IO.File]::ReadAllText($mapPath, $utf8NoBom)')
$lines.Add('        $oldVersion = Get-MemoryVersionFromText $mapText')
$lines.Add('        $snapshotPath = Join-Path $historyDir "全局知识地图_v$($oldVersion.Text).md"')
$lines.Add('        Copy-Item -LiteralPath $mapPath -Destination $snapshotPath -Force')
$lines.Add('')
$lines.Add('        $newVersion = "$($oldVersion.Major).$($oldVersion.Minor + 1).0"')
$lines.Add('        $header = "<!-- memory-version: $newVersion -->"')
$lines.Add('        if ($mapText -match ''^\s*<!--\s*memory-version:\s*\d+\.\d+\.\d+\s*-->'') {')
$lines.Add('            $mapText = [regex]::Replace(')
$lines.Add('                $mapText,')
$lines.Add('                ''^\s*<!--\s*memory-version:\s*\d+\.\d+\.\d+\s*-->'',')
$lines.Add('                $header,')
$lines.Add('                1')
$lines.Add('            )')
$lines.Add('        } else {')
$lines.Add('            $mapText = "$header`r`n" + $mapText')
$lines.Add('        }')
$lines.Add('    } else {')
$lines.Add('        $mapText = @"')
$lines.Add('<!-- memory-version: 1.0.0 -->')
$lines.Add('# 全局知识地图')
$lines.Add('')
$lines.Add('> 所有研究子项目的总索引，新建子项目时自动更新。')
$lines.Add('')
$lines.Add('| 话题 | 子项目文件夹 | 创建时间 | 状态 | 核心结论（一句话） |')
$lines.Add('|------|------------|---------|------|----------------|')
$lines.Add('"@')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    if ($mapText -notmatch [regex]::Escape("| $Topic | $FolderName |")) {')
$lines.Add('        $mapText = $mapText.TrimEnd() + "`r`n$row`r`n"')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    [System.IO.File]::WriteAllText($mapPath, $mapText, $utf8WithBom)')
$lines.Add('    Write-Host "[OK] Updated global knowledge map: $mapPath"')
$lines.Add('}')
$lines.Add('')
$lines.Add('$workspaceRoot = $null')
$lines.Add('if ($OutputRoot -eq "") {')
$lines.Add('    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path')
$lines.Add('    $searchDir = $scriptDir')
$lines.Add('    while ($searchDir) {')
$lines.Add('        if ((Test-Path (Join-Path $searchDir "output")) -and (Test-Path (Join-Path $searchDir ".history"))) {')
$lines.Add('            $workspaceRoot = $searchDir')
$lines.Add('            break')
$lines.Add('        }')
$lines.Add('        $parent = Split-Path $searchDir -Parent')
$lines.Add('        if ($parent -eq $searchDir) { break }')
$lines.Add('        $searchDir = $parent')
$lines.Add('    }')
$lines.Add('    if (-not $workspaceRoot) {')
$lines.Add('        Write-Error "Workspace root not found. Please specify -OutputRoot explicitly."')
$lines.Add('        exit 1')
$lines.Add('    }')
$lines.Add('    $OutputRoot = Join-Path $workspaceRoot "output"')
$lines.Add('} else {')
$lines.Add('    $outputRootFull = [System.IO.Path]::GetFullPath($OutputRoot)')
$lines.Add('    $workspaceRoot = Split-Path -Parent $outputRootFull')
$lines.Add('}')
$lines.Add('')
$lines.Add('$existingProjectNumbers = @(')
$lines.Add('    Get-ChildItem -Path $OutputRoot -Directory -ErrorAction SilentlyContinue |')
$lines.Add('        ForEach-Object {')
$lines.Add('            if ($_.Name -match ''^(\d+)_'') {')
$lines.Add('                [int]$matches[1]')
$lines.Add('            }')
$lines.Add('        }')
$lines.Add(') | Sort-Object -Descending')
$lines.Add('')
$lines.Add('$nextProjectNumber = if ($existingProjectNumbers.Count -gt 0) {')
$lines.Add('    $existingProjectNumbers[0] + 1')
$lines.Add('} else {')
$lines.Add('    1')
$lines.Add('}')
$lines.Add('')
$lines.Add('$projectNumber = "{0:D2}" -f $nextProjectNumber')
$lines.Add('$folderName = "${projectNumber}_${Topic}_v1.0.0"')
$lines.Add('$projectPath = Join-Path $OutputRoot $folderName')
$lines.Add('')
$lines.Add('if (Test-Path $projectPath) {')
$lines.Add('    Write-Error "Folder already exists: $projectPath"')
$lines.Add('    exit 1')
$lines.Add('}')
$lines.Add('')
$lines.Add('New-Item -ItemType Directory -Path $projectPath -Force | Out-Null')
$lines.Add('Write-Host "[OK] Created project folder: $projectPath"')
$lines.Add('')
$lines.Add('# Create three sub-folders (empty placeholders v0.0.0)')
$lines.Add('$subFolders = @("01_问题答疑_v0.0.0", "02_课题研究_v0.0.0", "03_代码程序_v0.0.0")')
$lines.Add('foreach ($sf in $subFolders) {')
$lines.Add('    $sfPath = Join-Path $projectPath $sf')
$lines.Add('    New-Item -ItemType Directory -Path $sfPath -Force | Out-Null')
$lines.Add('    Write-Host "[OK] Created sub-folder: $sf"')
$lines.Add('}')
$lines.Add('')
$lines.Add('$displayTimestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"')
$lines.Add('$versionRecordPath = Join-Path $projectPath "版本记录.md"')
$lines.Add('$versionRecordContent = @"')
$lines.Add('# 版本记录 · $Topic')
$lines.Add('')
$lines.Add('> 记录子项目的版本变更历史。')
$lines.Add('')
$lines.Add('---')
$lines.Add('')
$lines.Add('## v1.0.0 ($displayTimestamp)')
$lines.Add('')
$lines.Add('**变更类型**：MAJOR')
$lines.Add('**创建时间**：$displayTimestamp')
$lines.Add('**变更描述**：首次创建。')
$lines.Add('')
$lines.Add('**子文件变更明细**：')
$lines.Add('')
$lines.Add('| 文件 | 版本变更 | 变更描述 |')
$lines.Add('|------|---------|---------||')
$lines.Add('| （待填写） | | |')
$lines.Add('')
$lines.Add('---')
$lines.Add('')
$lines.Add('"@')
$lines.Add('[System.IO.File]::WriteAllText($versionRecordPath, $versionRecordContent, $utf8WithBom)')
$lines.Add('Write-Host "[OK] Created version record: $versionRecordPath"')
$lines.Add('')
$lines.Add('$catalogPath = Join-Path $projectPath "目录.md"')
$lines.Add('$catalogContent = @"')
$lines.Add('# 目录 · $Topic')
$lines.Add('')
$lines.Add('> 本子项目内所有内容文件的索引，按三个子文件夹分节列出。')
$lines.Add('')
$lines.Add('---')
$lines.Add('')
$lines.Add('## 01_问题答疑')
$lines.Add('')
$lines.Add('| # | 文件 | 说明 | 首次落盘 | 最近更新 |')
$lines.Add('|---|------|------|---------|---------|')
$lines.Add('| 待新增文件后填写 | | | | |')
$lines.Add('')
$lines.Add('---')
$lines.Add('')
$lines.Add('## 02_课题研究')
$lines.Add('')
$lines.Add('| # | 文件 | 说明 | 首次落盘 | 最近更新 |')
$lines.Add('|---|------|------|---------|---------|')
$lines.Add('| 待新增文件后填写 | | | | |')
$lines.Add('')
$lines.Add('---')
$lines.Add('')
$lines.Add('## 03_代码程序')
$lines.Add('')
$lines.Add('| # | 文件 | 说明 | 首次落盘 | 最近更新 |')
$lines.Add('|---|------|------|---------|---------|')
$lines.Add('| 待新增文件后填写 | | | | |')
$lines.Add('')
$lines.Add('"@')
$lines.Add('[System.IO.File]::WriteAllText($catalogPath, $catalogContent, $utf8WithBom)')
$lines.Add('Write-Host "[OK] Created catalog: $catalogPath"')
$lines.Add('')
$lines.Add('Update-GlobalKnowledgeMap -WorkspaceRoot $workspaceRoot -Topic $Topic -FolderName $folderName')
$lines.Add('')
$lines.Add('Write-Host ""')
$lines.Add('Write-Host "=========================================="')
$lines.Add('Write-Host "  New Sub-Project Created"')
$lines.Add('Write-Host "=========================================="')
$lines.Add('Write-Host "  Topic    : $Topic"')
$lines.Add('Write-Host "  Folder   : $folderName"')
$lines.Add('Write-Host "  Path     : $projectPath"')
$lines.Add('Write-Host "  Created  : $displayTimestamp"')
$lines.Add('Write-Host "=========================================="')
$lines.Add('Write-Host ""')
$lines.Add('Write-Host "Next: create files inside sub-folders of $projectPath"')

$finalContent = $lines -join "`r`n"
[System.IO.File]::WriteAllText($targetPath, $finalContent, $enc)
Write-Host "Written OK: $targetPath"
